version: '3.8'

services:
    mealorders:
        build: ./app
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - ./app/:/usr/src/app/
        ports:
            - 8000:8000
        env_file:
            - ./app/.env.dev
    meal-db:
        image: postgres:12-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=corner
            - POSTGRES_PASSWORD=corner
            - POSTGRES_DB=meal

volumes:
    postgres_data: