version: '3.8'

services:
    mealorders:
        build: ./app
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - ./app/:/usr/src/app/
        ports:
            - 8000:8000
        env_file:
            - ./app/.env.dev
        depends_on:
            - meal-db
            - redis
    meal-db:
        image: postgres:12-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=corner
            - POSTGRES_PASSWORD=corner
            - POSTGRES_DB=meal
    redis:
        image: redis:alpine
    celery:
        build: ./app
        command: celery -A cornerlunch worker -l INFO
        volumes:
            - ./app/:/usr/src/app/
        env_file:
            - ./app/.env.dev
        depends_on:
            - meal-db
            - redis


volumes:
    postgres_data: